// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd1L__UI-IfDWJS5mUktSMduDh9wTkiX0',
    appId: '1:205840379628:web:2ed8434667c4fc83767fc9',
    messagingSenderId: '205840379628',
    projectId: 'registration-form-app-b9fd9',
    authDomain: 'registration-form-app-b9fd9.firebaseapp.com',
    storageBucket: 'registration-form-app-b9fd9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASJngMelndgrqrLt4HppSAxtPnOPmKNSg',
    appId: '1:205840379628:android:8164b8b3e8fa6160767fc9',
    messagingSenderId: '205840379628',
    projectId: 'registration-form-app-b9fd9',
    storageBucket: 'registration-form-app-b9fd9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz0B6vE-t3ps-2X2sbJVjEL5ugBonKCpQ',
    appId: '1:205840379628:ios:b3110e0688154552767fc9',
    messagingSenderId: '205840379628',
    projectId: 'registration-form-app-b9fd9',
    storageBucket: 'registration-form-app-b9fd9.firebasestorage.app',
    iosBundleId: 'com.example.registrationForm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz0B6vE-t3ps-2X2sbJVjEL5ugBonKCpQ',
    appId: '1:205840379628:ios:b3110e0688154552767fc9',
    messagingSenderId: '205840379628',
    projectId: 'registration-form-app-b9fd9',
    storageBucket: 'registration-form-app-b9fd9.firebasestorage.app',
    iosBundleId: 'com.example.registrationForm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd1L__UI-IfDWJS5mUktSMduDh9wTkiX0',
    appId: '1:205840379628:web:c7f67b98060ff530767fc9',
    messagingSenderId: '205840379628',
    projectId: 'registration-form-app-b9fd9',
    authDomain: 'registration-form-app-b9fd9.firebaseapp.com',
    storageBucket: 'registration-form-app-b9fd9.firebasestorage.app',
  );
}
